apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: basex-data-claim
spec:
  storageClassName: local-storage
  accessModes:
    - ReadWriteMany
  volumeMode: Block
  resources:
    requests:
      storage: 10Gi