name: Semantic Versioning
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.5.0
      with:
        fetch-depth: 0
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0
      with:
        versionSpec: '5.x'
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0
    - name: Display GitVersion variables (without prefix)
      run: |
        echo "SemVer: ${{ env.semVer }}"
    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v5.0.3
      with:
        version_format: "${major}.${minor}.${patch}-pre${increment}"
